name: data
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.4
  printing: ^5.11.1
  intl: ^0.18.1
  get: ^4.7.2
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PolySans
      fonts:
        - asset: assets/images/fonts/PolySans Slim.ttf


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/appIcon.png"

